version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: banana-api
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/1.sql
    expose:
      - '3306'
  api:
    build: ./banana
    ports:
      - "5000:5000"
  scraper:
    build: ./libs
    ports:
      - "3000:3000"
volumes:
  db:
    driver: local