version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE='banana-api'
      - MYSQL_ROOT_PASSWORD='$BananaApi'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - '3306'
  scraper:
    build: ./libs
    ports:
      - "3000:3000"
    tty: true
volumes:
  db:
    driver: local